// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lrpfwqqusuhwtumoqmwy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxycGZ3cXF1c3Vod3R1bW9xbXd5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODM5NjMyMzksImV4cCI6MjA5OTUzOTIzOX0.u-k55jSm-2ELHyV8zoSEnHc4Pb2Z16pRSYkMJ-TvzME";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});